"use client";

import React from "react";
import ModuleDetailTemplate, {
  ModuleDetailData,
} from "@/app/components/ModuleDetailTemplate";
import {
  Target,
  UsersRound,
  Zap,
  BarChart3,
  Mail,
  TrendingUp,
  FileCheck2,
  CalendarCheck,
} from "lucide-react";

const crmData: ModuleDetailData = {
  slug: "crm",
  badge: "CRM Module",
  title: "Customer Relationship Management (CRM)",
  oneLinePromise: "360-degree customer pipeline, AI lead scoring, and automated deal forecasting.",
  description:
    "Empower your sales team with live deal tracking, automated lead qualification, omnichannel communication history, and seamless conversion from leads to sales orders.",
  painPoints: [
    {
      title: "Lost Prospects & Delayed Follow-Ups",
      description: "Manual lead tracking in spreadsheets causes qualified prospects to slip through the cracks without timely sales outreach.",
    },
    {
      title: "Inaccurate Sales Revenue Forecasting",
      description: "Relying on rep gut-feeling leads to unreliable pipeline projections and missed quarterly revenue targets.",
    },
    {
      title: "Scattered Customer Communication History",
      description: "Siloed emails, call notes, and WhatsApp messages prevent sales teams from seeing a complete 360-degree customer history.",
    },
  ],
  features: [
    {
      title: "Visual Drag-and-Drop Pipeline Management",
      description: "Track deals through customizable pipeline stages with automated probability scoring and stage velocity alerts.",
      icon: Target,
    },
    {
      title: "AI Predictive Lead Scoring & Territory Routing",
      description: "Prioritize high-intent leads automatically using AI behavioral scoring and route prospects to the right rep.",
      icon: Zap,
    },
    {
      title: "Omnichannel Email, Call & WhatsApp Sync",
      description: "Bi-directional sync with Google Workspace, Microsoft Outlook, and WhatsApp for zero manual communication logging.",
      icon: Mail,
    },
    {
      title: "1-Click Quote to Sales Order Bridge",
      description: "Convert approved CRM proposals into binding Sales Orders instantly without rekeying item SKUs or customer data.",
      icon: TrendingUp,
    },
    {
      title: "Customer 360-Degree Activity Timeline",
      description: "Unified activity view consolidating emails, meeting notes, quotations, purchase history, and support tickets.",
      icon: UsersRound,
    },
    {
      title: "Weighted Sales Revenue Forecasting",
      description: "Predict quarterly closed revenue using stage velocity algorithms and historical rep closure performance.",
      icon: BarChart3,
    },
    {
      title: "Automated Meeting Preparation & AI Summaries",
      description: "Receive pre-meeting briefing decks and automated post-call transcripts with action items generated by AI.",
      icon: CalendarCheck,
    },
    {
      title: "Custom Contract & SLA Renewal Reminders",
      description: "Trigger automated alerts before customer subscription or service contract renewals to maximize retention.",
      icon: FileCheck2,
    },
  ],
  workflowSteps: [
    {
      stepNumber: 1,
      title: "Lead Capture & AI Qualification",
      description: "Inbound web leads and campaigns automatically enter CRM, where AI assigns a win probability score.",
    },
    {
      stepNumber: 2,
      title: "Opportunity & Stage Progression",
      description: "Sales reps log meetings, emails, and requirements, moving deals forward on drag-and-drop Kanban boards.",
    },
    {
      stepNumber: 3,
      title: "Automated Quotation Delivery",
      description: "Reps generate branded proposals with 1-click price lookup and send them directly for customer sign-off.",
    },
    {
      stepNumber: 4,
      title: "Deal Closure & Sales Order Bridge",
      description: "Accepted proposals automatically convert into binding Sales Orders, reserving stock and triggering fulfillment.",
    },
  ],
  integrationFlow: {
    description:
      "CRM integrates directly with Sales & Order Management for instant quote conversion, Inventory Control for stock reservation, and Accounting & Finance for automated invoice generation.",
    connectedModules: ["Sales & Order Management", "Inventory Control", "Accounting & Finance"],
  },
  reports: [
    {
      name: "Sales Pipeline Velocity & Stage Conversion",
      description: "Tracks win rates, average deal cycle length, and bottleneck stages across sales pipelines.",
      category: "Pipeline Audit",
    },
    {
      name: "AI Lead Win Probability & Conversion Matrix",
      description: "Measures lead quality, channel conversion velocity, and AI score accuracy rates.",
      category: "Lead Analytics",
    },
    {
      name: "Sales Rep Activity & Quotas Attainment",
      description: "Itemizes calls, meetings logged, proposals sent, and revenue closed per account representative.",
      category: "Team Performance",
    },
    {
      name: "Weighted Sales Forecast & Cash Flow Projection",
      description: "Projects 30-60-90 day closed revenue based on pipeline stage probabilities.",
      category: "Executive",
    },
  ],
  ctaPitch:
    "Accelerate deal velocity, empower your sales team with AI lead scoring, and gain 100% pipeline visibility with Warrgyizmorsch CRM.",
};

export default function CrmModulePage() {
  return <ModuleDetailTemplate data={crmData} />;
}
